import Head from "next/head";
import TableData from "../components/Tabledata";
import { Suspense, useEffect, useState } from "react";
import { Spinner } from "../components/Spinner";
import Search from "../components/Search";
import { useSearchParams, usePathname, useRouter } from "next/navigation";
import { useDebouncedCallback } from "use-debounce";
import axios from "axios";

export default function Home() {
  const searchParams = useSearchParams();
  const pathname = usePathname();
  const { replace } = useRouter();
  const [employees, setEmployees] = useState([]);

  const handleSearch = useDebouncedCallback(async (term: string) => {
    const params = new URLSearchParams(searchParams);
    if (term) {
      params.set("query", term);
    } else {
      params.delete("query");
    }
    replace(`${pathname}?${params.toString()}`);

    await axios
      .get(`/api/action?query=${term}`)
      .then((res) => setEmployees(res.data));
  }, 300);

  const fetchData = async () => {
    await axios.get("/api/action").then((res) => setEmployees(res.data));
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex w-screen flex-col items-center justify-center py-20">
        <div className="mb-5 flex items-center justify-between gap-1">
          <h1 className="text-4xl font-bold">Employees</h1>
        </div>

        <div className="grid min-w-[52rem] items-center overflow-x-auto">
          <Search
            handleSearch={handleSearch}
            searchParams={searchParams}
            fetchData={fetchData}
          />

          <Suspense fallback={<Spinner />}>
            <TableData employees={employees} fetchData={fetchData} />
          </Suspense>
        </div>
      </div>
    </>
  );
}
